### ISSUE TITLE
Ask for help to customise for HP Microserver Gen8?

### ISSUE THREAD

**Issue by dan-burt** [gotvach/unraid-grub#1]
I cannot get my device to boot from the internal USB slot on the motherboard if I try to use the official Mac USB creator app.

The same USB flash disk, and others, have been used to boot it succesfully into Ubuntu Live CD. And I am using this environment to recreate a customised Grub bootloader for my device. It also cannot do UEFI.

First I followed this, which is a more generic Xubuntu config, but I pointed to the downloaded ZIP file, renamed as ISO extension:
https://github.com/ndeineko/grub2-bios-uefi-usb

Certainly, Grub is loading on boot using this approach.

However, I cannot get unRAID running. When I boot this environment, I got this error:
```
error: unknown filesystem.
error: you need to load the kernel first.
```

Then I searched for "unraid grub.cfg" and came across this repo.

Can I ask if you would be willing to help identify the changes needed for my config, and use this for a more universal guide?

I followed your steps assuming the boot partition & fdisk stuff didn't need to be repeated, and I could just operate with the USB device mounted under /media (in my case, others have used /mnt). When I boot this, all I get is a repeated item to the Grub Menu each time I select the default item.

From the active grub prompt, my disk is identified as (hd0,msdos1)

Folder structure:
```
/boot/grub/
/isos/unRAIDServer-6.11.5-x86_64.iso
/UNRAID/<extract of above iso>
```

My current /boot/grub/grub.cfg. I left previous configs in there, while trying stuff:

```
menuentry 'unRAID 6.11.5'{
	set isofile="/isos/unRAIDServer-6.11.5-x86_64.iso"
	set prefix=(hd0,1)/boot/grub
	set root=(hd0,1)
	insmod normal
	normal
	#search --set=root --file $isofile
	#rmmod tpm #uncomment if grub version is 2.04 in UEFI mode (see https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1851311)
	loopback isoloop $isofile
	linux (isoloop)/casper/vmlinuz locale=en_GB boot=casper iso-scan/filename=$isofile quiet --
	initrd (isoloop)/casper/initrd
}
```

I am not sure what other details you would need. Please ask.

**Comment by gotvach** [comment]
Hi,

Thanks for your interest in this. I'm happy to help out if I can.

Whilst I've not tried booting UNRAID from an iso in this way it seems like you might almost be there with the correct config.

Since you've reached the stage of booting GRUB, my initial thought is whether the `iso9660` GRUB module needs to be added to the list of modules installed? I suspect this might a reason for the `unknown filesystem` error due to it not knowing how mount the iso image.

It's been a while since I did a fresh USB build. A couple of quick questions:

1. I'm a little confused about the folder structure presented - is that what is looks like from the mounted USB drive at /media/ or from the grub command prompt? I wouldn't expect `/UNRAID/<extract of above iso>` to be there.
2. The ISO is unpacked but at the same time the grub config suggests running unRAID from the ISO rather than the unpacked files. Have I misunderstood?

Maybe my [original document](https://github.com/gotvach/unraid-grub#install-unraid-software) could be clearer since the unpacking of the (zip in my case) occurs at the root of the USB drive mount point which was `/media/grant/UNRAID`. Meaning there would not be a directory UNRAID on the USB drive.

I'd expect to see something more like:

```
/media/USB_drive/boot/grub
/media/USB_drive/<unpacked contents of unRAIDServer-6.11.5-x86_64.iso>
```
Although if it turns out that the iso has a directory called UNRAID then that might explain it.

As it turns out I'm just upgrading my system to 6.11.5 today. I might take a look at taking the iso approach later on to cover that use case.

**Comment by gotvach** [comment]
After some testing I have had some success locally with this.

## Extra grub modules

For the ISO use case both `iso9660` and `loopback` grub modules are required.

```
grub-install --target=i386-pc --boot-directory unraid-volume/boot/ --modules="usb ls loopback help part_msdos iso9660" --allow-floppy --install-modules="test ls usb normal loopback help iso9660 linux linux16" -v /dev/sda
```

## Grub config

I assume the ISO image was generated from the zip package since I cannot find an official ISO.
In which case the kernel image is `bzimage` and the ramdisk `bzroot`.

Minimal working config:
```
menuentry 'unRAID 6.11.5' {
        set isofile="/isos/unRAIDServer-6.11.5-x86_64.iso"
	set root=(hd0,1)
	loopback loop $isofile
	linux (loop)/bzimage
	initrd (loop)/bzroot
}
```

**Comment by dan-burt** [comment]
The good news - I got it working!

I think the root cause was using USB2.0 drives to boot from. I think I got distracted / confused with the combinations of drives I used in this process. Because I only have this Intel CPU computer in the house, I had to boot it using a Ubuntu Live with 1 drive. I used my slower Sandisk Cruzer USB2.0 for this purpose. For some reason, because I booted from a faster Samsung drive, I wanted to use this. And it was with this device I was getting all these errors. I bought a 2nd Sandisk 2.0 device, and used that to boot from - 1 for Ubuntu Live, the other for unRAID.

Second, I used your guide alongside another that detailed the `fdsisk` commands first, then switched to yours. Each used different mount paths, which I tried to fix incorrectly.

The unRAID forum thread:
https://forums.unraid.net/topic/134288-days-trying-to-unraid-boot-a-hpe-microserver-gen8/#comment-1220691

The other `fdisk` guide:
https://github.com/ndeineko/grub2-bios-uefi-usb

Can I pass recommendations to update / tweak your guide?

- I retained using the "W95 FAT32 (LBA)" partition type from your guide, not the other link. So `0c` in the `fdisk` commands, not `ef`.
- After creating the FAT32 partition filesystem, I manually label the partition device (not the disk), so `/dev/sdd1` in my particular case.
- When I `sudo mount` this device, I used the path in the other guide at `/mnt`. I think I got confused with your mount path and the unzipped folder structure, so I had `sudo unzip -d /mnt/ unRAID....zip`, but the other guide used `/mnt` so it was helpful to adjust my paths.
- I didn't use / need the `device.map` file.
- the `grub-syslinux2cfg` output turned out to be wrong for me, resulting in a triple-forward slash, that I needed to edit back to being off of the root folder, i.e. `'/bzimage'`
- I ran all 3 `grub-install` commands, though I have no idea if I needed to for the Microserver. I kept it at the more basic configuration compared to yours, with the extra `--modules ...` or `--install-modules`
- Syntax error in your `grub-install` command, should be `--boot-directory=/mnt/boot/` (in my case)
